### ISSUE TITLE
How to utilize the singularity for training and evaluation

### ISSUE THREAD

**Issue by TeleeMa** [cshizhe/hiveformer#3]
Hi Dr. Chen @cshizhe, 

Thank you for your great work.

I am new to the singularity, and I have a few questions about the usage. I would appreciate it if you can help.

1. I used the interactive mode of singularity with `singularity shell --nv vlc_rlbench.sif`. I found the environemnt of hiveformer in python3.9, however, I could not use the basic command of linux like _vim_, _lsb_release -a_. So should I install these linux-based commands by myself in singularity? Or I should start a container of singularity instead of using the interactive mode?
2. Is it right that the singularity does not contain the CoppeliaSim and I should build by myself?
3. As I use headless devices, the `nvidia-xconfig` cannot be found in the singularity, which is required by PyRep in [PyRep#running-headless](https://github.com/stepjam/PyRep#running-headless). Do you have any suggestions about this?

Best regards.

**Comment by cshizhe** [comment]
- If you have sudo privilege on the headless machine, I would suggest you follow the way in PyRep to setup the environments by yourself which is more convenient;
- Otherwise, you could use our singularity image. The image only contains minimum dependencies to run our codes including the CoppeliaSim (in the /opt directory). If you want to install other packages, you could build a sandbox on top of it.  Please visit singularity website (https://docs.sylabs.io/guides/3.5/user-guide/quick_start.html#quick-start) for more information of using singularity.

**Comment by TeleeMa** [comment]
Thank you for your reply. I will try again and I close the issue.
